### ISSUE TITLE
Shows dont populate

### ISSUE THREAD

**Issue by tetoNidan** [lottaboost/plugin.video.tyt#1]
Just downloaded your app and cant get the shows to populate. Just an empty screen selection with a [Next] button, no matter what show I choose to view episodes from. What am I doing wrong? The only thing I can think of is it's not connecting to the network? Just a guess though. Internet is connected.

**Comment by lottaboost** [comment]
When they updated their page a few months ago, it broke the plug-in.  Unfortunately, right now, I'm way too busy to update the plug-in.

**Comment by tetoNidan** [comment]
Im getting a new hard drive in a couple days, after I set up my new OS I will pull and see if I cant get us going again.

**Comment by cyberhiker** [comment]
Any chance there you found some time to work on this?

**Comment by tetoNidan** [comment]
Im sory i havent. Kind of pulled all my code and left github.

**Comment by lottaboost** [comment]
I have abandoned the plug-in.  I don't have time to work on it, and no longer use it anyways (using a NVidia shield box and TYTs Android app).
