### ISSUE TITLE
Path for Members Live show incorrect

### ISSUE THREAD

**Issue by jonathanhirschman** [lottaboost/plugin.video.tyt#2]
First, thanks so much for writing this add-on, much appreciated.

When trying to access Members Live Show, the add-on is creating an incorrect path. In the context window for the show:

Members Live Show
Genre: News
Runtime: 44 Minutes
Path: plugin://plugin.video.youtube/play/?video_id=None

The regular live stream works fine.

Thanks!

**Comment by lottaboost** [comment]
Thanks for letting me know, I'll fix it as soon as I can.

Brian

**Comment by jonathanhirschman** [comment]
Thanks so much. Looks like there's an issue with the regular live stream, too - TYT must be doing some renovations :( Very much appreciate your work!

**Comment by lottaboost** [comment]
Looked at it today, and both streams were working.  They must have been trying something last week, or injected crappy code.
